name: Twitter Automation tests pipeline

on:
 push:
  branches:
  - main
 pull_request:
  branches:
   - main
   
jobs:
 build:
  runs-on: ubuntu-latest
  
  env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  
  steps:
   - name: Checkout Code
     uses: actions/checkout@v3
     
   - name: Set up .NET Core
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '8.x'
    
   - name: Install dependencies
     run: dotnet restore ./Tests/TestProject1.sln
     
     
   - name: Build
     run: dotnet build ./Tests/TestProject1.sln --no-restore
    
    
   - name: Test
     run: dotnet test ./Tests/TestProject1.sln --no-build --verbosity normal